openapi: 3.0.3
info:
  title: Payments API
  description: API for processing payment updates via Stripe integration in churn prevention POC
  version: 1.0.0

paths:
  /api/payments/validate-card:
    post:
      summary: Validate new payment card details
      description: Real-time validation of card information before processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cardNumber:
                  type: string
                  pattern: '^[0-9]{13,19}$'
                  example: "4242424242424242"
                expiryMonth:
                  type: integer
                  minimum: 1
                  maximum: 12
                  example: 12
                expiryYear:
                  type: integer
                  minimum: 2025
                  example: 2027
                cvc:
                  type: string
                  pattern: '^[0-9]{3,4}$'
                  example: "123"
              required:
                - cardNumber
                - expiryMonth
                - expiryYear
                - cvc
      responses:
        '200':
          description: Card validation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: true
                  cardType:
                    type: string
                    enum: [visa, mastercard, amex, discover]
                    example: "visa"
                  lastFourDigits:
                    type: string
                    example: "4242"
        '400':
          description: Invalid card details
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: false
                  errors:
                    type: array
                    items:
                      type: string
                    example: ["Invalid card number", "Card expired"]

  /api/payments/update-method:
    post:
      summary: Update customer payment method
      description: Process new payment method using Stripe test mode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  example: "cust_12345"
                sessionId:
                  type: string
                  example: "session_abc123"
                cardNumber:
                  type: string
                  pattern: '^[0-9]{13,19}$'
                expiryMonth:
                  type: integer
                  minimum: 1
                  maximum: 12
                expiryYear:
                  type: integer
                  minimum: 2025
                cvc:
                  type: string
                  pattern: '^[0-9]{3,4}$'
                billingAddress:
                  $ref: '#/components/schemas/BillingAddress'
              required:
                - customerId
                - sessionId
                - cardNumber
                - expiryMonth
                - expiryYear
                - cvc
      responses:
        '200':
          description: Payment method updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  paymentMethod:
                    $ref: '#/components/schemas/PaymentMethodResult'
                  stripeCustomerId:
                    type: string
                    example: "cus_stripe123"
                  message:
                    type: string
                    example: "Payment method updated successfully"
        '400':
          description: Invalid payment information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentError'
        '402':
          description: Payment processing failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentError'
        '500':
          description: Stripe API error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentError'

  /api/payments/test-charge:
    post:
      summary: Process test charge to verify payment method
      description: Minimal charge ($1) to confirm payment method works
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  example: "cust_12345"
                paymentMethodId:
                  type: string
                  example: "pm_67890"
                amount:
                  type: integer
                  description: Amount in cents
                  minimum: 100
                  maximum: 100
                  example: 100
              required:
                - customerId
                - paymentMethodId
                - amount
      responses:
        '200':
          description: Test charge successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  chargeId:
                    type: string
                    example: "ch_test123"
                  refundId:
                    type: string
                    example: "re_test123"
                    description: Automatic refund ID
                  message:
                    type: string
                    example: "Payment method verified and refunded"
        '402':
          description: Test charge failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentError'

  /api/payments/stripe-webhook:
    post:
      summary: Handle Stripe webhook events
      description: Process real-time payment status updates from Stripe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Stripe webhook payload
      responses:
        '200':
          description: Webhook processed successfully
        '400':
          description: Invalid webhook signature or payload

components:
  schemas:
    BillingAddress:
      type: object
      properties:
        line1:
          type: string
          example: "123 Main St"
        line2:
          type: string
          nullable: true
          example: "Apt 4B"
        city:
          type: string
          example: "San Francisco"
        state:
          type: string
          example: "CA"
        postalCode:
          type: string
          example: "94105"
        country:
          type: string
          pattern: '^[A-Z]{2}$'
          example: "US"
      required:
        - line1
        - city
        - state
        - postalCode
        - country

    PaymentMethodResult:
      type: object
      properties:
        id:
          type: string
          example: "pm_new123"
        cardType:
          type: string
          enum: [visa, mastercard, amex, discover]
          example: "visa"
        lastFourDigits:
          type: string
          example: "4242"
        expiryMonth:
          type: integer
          example: 12
        expiryYear:
          type: integer
          example: 2027
        status:
          type: string
          enum: [active, expired, failed, invalid]
          example: "active"
      required:
        - id
        - cardType
        - lastFourDigits
        - expiryMonth
        - expiryYear
        - status

    PaymentError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              enum: [card_declined, invalid_card, processing_error, stripe_error]
              example: "card_declined"
            message:
              type: string
              example: "Your card was declined"
            details:
              type: string
              nullable: true
              example: "Insufficient funds"
            suggestedAction:
              type: string
              enum: [try_different_card, contact_bank, retry_later]
              example: "try_different_card"
      required:
        - success
        - error